-- 코드를 입력하세요
WITH DIFFTABLE AS (
    SELECT A.ANIMAL_ID, DATEDIFF(B.DATETIME, A.DATETIME) AS DIFF
    FROM ANIMAL_INS A
    JOIN ANIMAL_OUTS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
)

SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS A
JOIN DIFFTABLE B
ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY B.DIFF DESC
LIMIT 2;