-- 코드를 작성해주세요
SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR, 
    ABS(SIZE_OF_COLONY - MAX_SIZE) AS YEAR_DEV,
    ID
FROM ECOLI_DATA E
JOIN (  -- 연도별 최대 값을 가지는 테이블과 결합
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) M
ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR, YEAR_DEV


