-- 코드를 입력하세요
-- SELECT b.REST_ID, b.REST_NAME, b.FOOD_TYPE, b.FAVORITES, b.ADDRESS, ROUND(AVG(a.REVIEW_SCORE), 2) AS REVIEW
-- FROM REST_REVIEW a JOIN REST_INFO b ON a.REST_ID = b.REST_ID
-- WHERE b.ADDRESS LIKE "서울%"
-- ORDER BY REVIEW DESC, b.FAVORITES DESC;

SELECT b.REST_ID, b.REST_NAME, b.FOOD_TYPE, b.FAVORITES, b.ADDRESS, ROUND(AVG(a.REVIEW_SCORE), 2) AS REVIEW_SCORE
FROM REST_REVIEW a JOIN REST_INFO b ON a.REST_ID = b.REST_ID
GROUP BY b.REST_ID
HAVING b.ADDRESS LIKE '서울%'
ORDER BY ROUND(AVG(a.REVIEW_SCORE), 2) DESC, b.FAVORITES DESC;